name: 'Alpine'

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        release: [
          {distro: "alpine", version: "3.16"},
          {distro: "alpine", version: "3.17"},
          {distro: "alpine", version: "3.18"},
          {distro: "alpine", version: "3.19"},
          {distro: "alpine", version: "edge"}
        ]
        os: [
          {arch: "aarch64", builder: "warp-ubuntu-latest-arm64-2x"},
          {arch: "x86_64", builder: "warp-ubuntu-latest-x64-2x"}
        ]

    runs-on: ${{matrix.os.builder}}
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Distrobuilder
        run: |
          sudo snap install distrobuilder --classic

      - name: Build Image
        run: |
          sudo distrobuilder build-incus images/${{matrix.release.distro}}.yml rootfs -o image.serial=${{ github.run_id }} -o image.architecture=${{matrix.os.arch}} -o image.release=${{matrix.release.version}}

      - name: Setup IcePAK
        uses: upmaru/icepak@develop

      - name: Push
        run: |
          icepak push --path rootfs  --os ${{matrix.release.distro}} --arch ${{matrix.os.arch}} --release ${{matrix.release.version}} --variant default
        env:
          POLAR_AUTH_KEY: ${{ secrets.POLAR_AUTH_KEY }}
          POLAR_ENDPOINT: ${{ env.POLAR_ENDPOINT }}
