name: 'Build'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: warp-ubuntu-latest-arm64-2x
    strategy:
      matrix:
        release: ["3.16", "3.17", "3.18", "3.19", "edge"]
        arch: ["x86_64", "aarch64"]

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Distrobuilder
        run: |
          sudo snap install distrobuilder --classic

      - name: Build Image
        run: |
          sudo distrobuilder build-incus alpine.yml rootfs -o image.serial=${{ github.run_id }} -o image.architecture=${{matrix.arch}} -o image.release=${{matrix.release}}