name: 'Debian'

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        release: [
          {distro: "debian", version: "bookworm"},
          {distro: "debian", version: "sid"}
        ]
        os: [
          {arch: "arm64", builder: "nscloud-ubuntu-22.04-arm64-2x4"},
          {arch: "amd64", builder: "nscloud-ubuntu-22.04-amd64-2x4"}
        ]

    runs-on: ${{matrix.os.builder}}
    env:
      ImageOS: ubuntu22
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup IcePAK
        uses: upmaru/icepak@v0
        with:
          alpine: v3.19
          arch: ${{matrix.os.arch}}

      - name: Generate Serial
        id: generate-serial
        run: |
          echo "serial=$(date +'%Y%m%d')-$GITHUB_RUN_NUMBER" >> $GITHUB_OUTPUT

      - name: Build Image
        run: |
          sudo apt-get install debootstrap -y
          sudo ~/go/bin/distrobuilder build-incus images/${{matrix.release.distro}}.yml rootfs -o image.serial=${{ steps.generate-serial.outputs.serial }} -o image.architecture=${{matrix.os.arch}} -o image.release=${{matrix.release.version}} -o source.url="http://ftp.us.debian.org/debian"

      - name: Push
        run: |
          icepak push --path rootfs --serial ${{ steps.generate-serial.outputs.serial }}  --os ${{matrix.release.distro}} --arch ${{matrix.os.arch}} --release ${{matrix.release.version}} --variant default
        shell: alpine.sh {0}
        env:
          POLAR_AUTH_TOKEN: ${{ secrets.POLAR_AUTH_TOKEN }}
          POLAR_ENDPOINT: ${{ vars.POLAR_ENDPOINT }}